name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:      
    
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        
    - uses: actions/checkout@v3
    - name: docker build
      run: | 
        docker build . --file Dockerfile --tag ohrafaelmartins/organize:latest
    
    - name: docker push
      run: | 
        docker push ohrafaelmartins/organize:latest
  
  push:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash

    steps:      
    
    - name: docker push
      run: | 
        docker push ohrafaelmartins/organize:latest
